// ISO 3166-1 alpha-2 country codes
// Lista completa dei paesi con codici ISO per il campo Country

export interface CountryOption {
  value: string; // ISO code
  label: string; // Display name with ISO code
}

export const ISO_COUNTRIES: CountryOption[] = [
  { value: 'AD', label: 'Andorra (AD)' },
  { value: 'AE', label: 'United Arab Emirates (AE)' },
  { value: 'AF', label: 'Afghanistan (AF)' },
  { value: 'AG', label: 'Antigua and Barbuda (AG)' },
  { value: 'AI', label: 'Anguilla (AI)' },
  { value: 'AL', label: 'Albania (AL)' },
  { value: 'AM', label: 'Armenia (AM)' },
  { value: 'AO', label: 'Angola (AO)' },
  { value: 'AQ', label: 'Antarctica (AQ)' },
  { value: 'AR', label: 'Argentina (AR)' },
  { value: 'AS', label: 'American Samoa (AS)' },
  { value: 'AT', label: 'Austria (AT)' },
  { value: 'AU', label: 'Australia (AU)' },
  { value: 'AW', label: 'Aruba (AW)' },
  { value: 'AX', label: 'Åland Islands (AX)' },
  { value: 'AZ', label: 'Azerbaijan (AZ)' },
  { value: 'BA', label: 'Bosnia and Herzegovina (BA)' },
  { value: 'BB', label: 'Barbados (BB)' },
  { value: 'BD', label: 'Bangladesh (BD)' },
  { value: 'BE', label: 'Belgium (BE)' },
  { value: 'BF', label: 'Burkina Faso (BF)' },
  { value: 'BG', label: 'Bulgaria (BG)' },
  { value: 'BH', label: 'Bahrain (BH)' },
  { value: 'BI', label: 'Burundi (BI)' },
  { value: 'BJ', label: 'Benin (BJ)' },
  { value: 'BL', label: 'Saint Barthélemy (BL)' },
  { value: 'BM', label: 'Bermuda (BM)' },
  { value: 'BN', label: 'Brunei (BN)' },
  { value: 'BO', label: 'Bolivia (BO)' },
  { value: 'BQ', label: 'Caribbean Netherlands (BQ)' },
  { value: 'BR', label: 'Brazil (BR)' },
  { value: 'BS', label: 'Bahamas (BS)' },
  { value: 'BT', label: 'Bhutan (BT)' },
  { value: 'BV', label: 'Bouvet Island (BV)' },
  { value: 'BW', label: 'Botswana (BW)' },
  { value: 'BY', label: 'Belarus (BY)' },
  { value: 'BZ', label: 'Belize (BZ)' },
  { value: 'CA', label: 'Canada (CA)' },
  { value: 'CC', label: 'Cocos Islands (CC)' },
  { value: 'CD', label: 'Democratic Republic of the Congo (CD)' },
  { value: 'CF', label: 'Central African Republic (CF)' },
  { value: 'CG', label: 'Republic of the Congo (CG)' },
  { value: 'CH', label: 'Switzerland (CH)' },
  { value: 'CI', label: 'Côte d\'Ivoire (CI)' },
  { value: 'CK', label: 'Cook Islands (CK)' },
  { value: 'CL', label: 'Chile (CL)' },
  { value: 'CM', label: 'Cameroon (CM)' },
  { value: 'CN', label: 'China (CN)' },
  { value: 'CO', label: 'Colombia (CO)' },
  { value: 'CR', label: 'Costa Rica (CR)' },
  { value: 'CU', label: 'Cuba (CU)' },
  { value: 'CV', label: 'Cape Verde (CV)' },
  { value: 'CW', label: 'Curaçao (CW)' },
  { value: 'CX', label: 'Christmas Island (CX)' },
  { value: 'CY', label: 'Cyprus (CY)' },
  { value: 'CZ', label: 'Czech Republic (CZ)' },
  { value: 'DE', label: 'Germany (DE)' },
  { value: 'DJ', label: 'Djibouti (DJ)' },
  { value: 'DK', label: 'Denmark (DK)' },
  { value: 'DM', label: 'Dominica (DM)' },
  { value: 'DO', label: 'Dominican Republic (DO)' },
  { value: 'DZ', label: 'Algeria (DZ)' },
  { value: 'EC', label: 'Ecuador (EC)' },
  { value: 'EE', label: 'Estonia (EE)' },
  { value: 'EG', label: 'Egypt (EG)' },
  { value: 'EH', label: 'Western Sahara (EH)' },
  { value: 'ER', label: 'Eritrea (ER)' },
  { value: 'ES', label: 'Spain (ES)' },
  { value: 'ET', label: 'Ethiopia (ET)' },
  { value: 'FI', label: 'Finland (FI)' },
  { value: 'FJ', label: 'Fiji (FJ)' },
  { value: 'FK', label: 'Falkland Islands (FK)' },
  { value: 'FM', label: 'Micronesia (FM)' },
  { value: 'FO', label: 'Faroe Islands (FO)' },
  { value: 'FR', label: 'France (FR)' },
  { value: 'GA', label: 'Gabon (GA)' },
  { value: 'GB', label: 'United Kingdom (GB)' },
  { value: 'GD', label: 'Grenada (GD)' },
  { value: 'GE', label: 'Georgia (GE)' },
  { value: 'GF', label: 'French Guiana (GF)' },
  { value: 'GG', label: 'Guernsey (GG)' },
  { value: 'GH', label: 'Ghana (GH)' },
  { value: 'GI', label: 'Gibraltar (GI)' },
  { value: 'GL', label: 'Greenland (GL)' },
  { value: 'GM', label: 'Gambia (GM)' },
  { value: 'GN', label: 'Guinea (GN)' },
  { value: 'GP', label: 'Guadeloupe (GP)' },
  { value: 'GQ', label: 'Equatorial Guinea (GQ)' },
  { value: 'GR', label: 'Greece (GR)' },
  { value: 'GS', label: 'South Georgia and the South Sandwich Islands (GS)' },
  { value: 'GT', label: 'Guatemala (GT)' },
  { value: 'GU', label: 'Guam (GU)' },
  { value: 'GW', label: 'Guinea-Bissau (GW)' },
  { value: 'GY', label: 'Guyana (GY)' },
  { value: 'HK', label: 'Hong Kong (HK)' },
  { value: 'HM', label: 'Heard Island and McDonald Islands (HM)' },
  { value: 'HN', label: 'Honduras (HN)' },
  { value: 'HR', label: 'Croatia (HR)' },
  { value: 'HT', label: 'Haiti (HT)' },
  { value: 'HU', label: 'Hungary (HU)' },
  { value: 'ID', label: 'Indonesia (ID)' },
  { value: 'IE', label: 'Ireland (IE)' },
  { value: 'IL', label: 'Israel (IL)' },
  { value: 'IM', label: 'Isle of Man (IM)' },
  { value: 'IN', label: 'India (IN)' },
  { value: 'IO', label: 'British Indian Ocean Territory (IO)' },
  { value: 'IQ', label: 'Iraq (IQ)' },
  { value: 'IR', label: 'Iran (IR)' },
  { value: 'IS', label: 'Iceland (IS)' },
  { value: 'IT', label: 'Italy (IT)' },
  { value: 'JE', label: 'Jersey (JE)' },
  { value: 'JM', label: 'Jamaica (JM)' },
  { value: 'JO', label: 'Jordan (JO)' },
  { value: 'JP', label: 'Japan (JP)' },
  { value: 'KE', label: 'Kenya (KE)' },
  { value: 'KG', label: 'Kyrgyzstan (KG)' },
  { value: 'KH', label: 'Cambodia (KH)' },
  { value: 'KI', label: 'Kiribati (KI)' },
  { value: 'KM', label: 'Comoros (KM)' },
  { value: 'KN', label: 'Saint Kitts and Nevis (KN)' },
  { value: 'KP', label: 'North Korea (KP)' },
  { value: 'KR', label: 'South Korea (KR)' },
  { value: 'KW', label: 'Kuwait (KW)' },
  { value: 'KY', label: 'Cayman Islands (KY)' },
  { value: 'KZ', label: 'Kazakhstan (KZ)' },
  { value: 'LA', label: 'Laos (LA)' },
  { value: 'LB', label: 'Lebanon (LB)' },
  { value: 'LC', label: 'Saint Lucia (LC)' },
  { value: 'LI', label: 'Liechtenstein (LI)' },
  { value: 'LK', label: 'Sri Lanka (LK)' },
  { value: 'LR', label: 'Liberia (LR)' },
  { value: 'LS', label: 'Lesotho (LS)' },
  { value: 'LT', label: 'Lithuania (LT)' },
  { value: 'LU', label: 'Luxembourg (LU)' },
  { value: 'LV', label: 'Latvia (LV)' },
  { value: 'LY', label: 'Libya (LY)' },
  { value: 'MA', label: 'Morocco (MA)' },
  { value: 'MC', label: 'Monaco (MC)' },
  { value: 'MD', label: 'Moldova (MD)' },
  { value: 'ME', label: 'Montenegro (ME)' },
  { value: 'MF', label: 'Saint Martin (MF)' },
  { value: 'MG', label: 'Madagascar (MG)' },
  { value: 'MH', label: 'Marshall Islands (MH)' },
  { value: 'MK', label: 'North Macedonia (MK)' },
  { value: 'ML', label: 'Mali (ML)' },
  { value: 'MM', label: 'Myanmar (MM)' },
  { value: 'MN', label: 'Mongolia (MN)' },
  { value: 'MO', label: 'Macao (MO)' },
  { value: 'MP', label: 'Northern Mariana Islands (MP)' },
  { value: 'MQ', label: 'Martinique (MQ)' },
  { value: 'MR', label: 'Mauritania (MR)' },
  { value: 'MS', label: 'Montserrat (MS)' },
  { value: 'MT', label: 'Malta (MT)' },
  { value: 'MU', label: 'Mauritius (MU)' },
  { value: 'MV', label: 'Maldives (MV)' },
  { value: 'MW', label: 'Malawi (MW)' },
  { value: 'MX', label: 'Mexico (MX)' },
  { value: 'MY', label: 'Malaysia (MY)' },
  { value: 'MZ', label: 'Mozambique (MZ)' },
  { value: 'NA', label: 'Namibia (NA)' },
  { value: 'NC', label: 'New Caledonia (NC)' },
  { value: 'NE', label: 'Niger (NE)' },
  { value: 'NF', label: 'Norfolk Island (NF)' },
  { value: 'NG', label: 'Nigeria (NG)' },
  { value: 'NI', label: 'Nicaragua (NI)' },
  { value: 'NL', label: 'Netherlands (NL)' },
  { value: 'NO', label: 'Norway (NO)' },
  { value: 'NP', label: 'Nepal (NP)' },
  { value: 'NR', label: 'Nauru (NR)' },
  { value: 'NU', label: 'Niue (NU)' },
  { value: 'NZ', label: 'New Zealand (NZ)' },
  { value: 'OM', label: 'Oman (OM)' },
  { value: 'PA', label: 'Panama (PA)' },
  { value: 'PE', label: 'Peru (PE)' },
  { value: 'PF', label: 'French Polynesia (PF)' },
  { value: 'PG', label: 'Papua New Guinea (PG)' },
  { value: 'PH', label: 'Philippines (PH)' },
  { value: 'PK', label: 'Pakistan (PK)' },
  { value: 'PL', label: 'Poland (PL)' },
  { value: 'PM', label: 'Saint Pierre and Miquelon (PM)' },
  { value: 'PN', label: 'Pitcairn (PN)' },
  { value: 'PR', label: 'Puerto Rico (PR)' },
  { value: 'PS', label: 'Palestine (PS)' },
  { value: 'PT', label: 'Portugal (PT)' },
  { value: 'PW', label: 'Palau (PW)' },
  { value: 'PY', label: 'Paraguay (PY)' },
  { value: 'QA', label: 'Qatar (QA)' },
  { value: 'RE', label: 'Réunion (RE)' },
  { value: 'RO', label: 'Romania (RO)' },
  { value: 'RS', label: 'Serbia (RS)' },
  { value: 'RU', label: 'Russia (RU)' },
  { value: 'RW', label: 'Rwanda (RW)' },
  { value: 'SA', label: 'Saudi Arabia (SA)' },
  { value: 'SB', label: 'Solomon Islands (SB)' },
  { value: 'SC', label: 'Seychelles (SC)' },
  { value: 'SD', label: 'Sudan (SD)' },
  { value: 'SE', label: 'Sweden (SE)' },
  { value: 'SG', label: 'Singapore (SG)' },
  { value: 'SH', label: 'Saint Helena (SH)' },
  { value: 'SI', label: 'Slovenia (SI)' },
  { value: 'SJ', label: 'Svalbard and Jan Mayen (SJ)' },
  { value: 'SK', label: 'Slovakia (SK)' },
  { value: 'SL', label: 'Sierra Leone (SL)' },
  { value: 'SM', label: 'San Marino (SM)' },
  { value: 'SN', label: 'Senegal (SN)' },
  { value: 'SO', label: 'Somalia (SO)' },
  { value: 'SR', label: 'Suriname (SR)' },
  { value: 'SS', label: 'South Sudan (SS)' },
  { value: 'ST', label: 'São Tomé and Príncipe (ST)' },
  { value: 'SV', label: 'El Salvador (SV)' },
  { value: 'SX', label: 'Sint Maarten (SX)' },
  { value: 'SY', label: 'Syria (SY)' },
  { value: 'SZ', label: 'Eswatini (SZ)' },
  { value: 'TC', label: 'Turks and Caicos Islands (TC)' },
  { value: 'TD', label: 'Chad (TD)' },
  { value: 'TF', label: 'French Southern Territories (TF)' },
  { value: 'TG', label: 'Togo (TG)' },
  { value: 'TH', label: 'Thailand (TH)' },
  { value: 'TJ', label: 'Tajikistan (TJ)' },
  { value: 'TK', label: 'Tokelau (TK)' },
  { value: 'TL', label: 'Timor-Leste (TL)' },
  { value: 'TM', label: 'Turkmenistan (TM)' },
  { value: 'TN', label: 'Tunisia (TN)' },
  { value: 'TO', label: 'Tonga (TO)' },
  { value: 'TR', label: 'Turkey (TR)' },
  { value: 'TT', label: 'Trinidad and Tobago (TT)' },
  { value: 'TV', label: 'Tuvalu (TV)' },
  { value: 'TW', label: 'Taiwan (TW)' },
  { value: 'TZ', label: 'Tanzania (TZ)' },
  { value: 'UA', label: 'Ukraine (UA)' },
  { value: 'UG', label: 'Uganda (UG)' },
  { value: 'UM', label: 'United States Minor Outlying Islands (UM)' },
  { value: 'US', label: 'United States (US)' },
  { value: 'UY', label: 'Uruguay (UY)' },
  { value: 'UZ', label: 'Uzbekistan (UZ)' },
  { value: 'VA', label: 'Vatican City (VA)' },
  { value: 'VC', label: 'Saint Vincent and the Grenadines (VC)' },
  { value: 'VE', label: 'Venezuela (VE)' },
  { value: 'VG', label: 'British Virgin Islands (VG)' },
  { value: 'VI', label: 'U.S. Virgin Islands (VI)' },
  { value: 'VN', label: 'Vietnam (VN)' },
  { value: 'VU', label: 'Vanuatu (VU)' },
  { value: 'WF', label: 'Wallis and Futuna (WF)' },
  { value: 'WS', label: 'Samoa (WS)' },
  { value: 'YE', label: 'Yemen (YE)' },
  { value: 'YT', label: 'Mayotte (YT)' },
  { value: 'ZA', label: 'South Africa (ZA)' },
  { value: 'ZM', label: 'Zambia (ZM)' },
  { value: 'ZW', label: 'Zimbabwe (ZW)' }
];

// Most common countries for quick access (optional)
export const COMMON_COUNTRIES: CountryOption[] = [
  { value: 'IT', label: 'Italy (IT)' },
  { value: 'US', label: 'United States (US)' },
  { value: 'DE', label: 'Germany (DE)' },
  { value: 'FR', label: 'France (FR)' },
  { value: 'GB', label: 'United Kingdom (GB)' },
  { value: 'ES', label: 'Spain (ES)' },
  { value: 'CH', label: 'Switzerland (CH)' },
  { value: 'AT', label: 'Austria (AT)' },
  { value: 'NL', label: 'Netherlands (NL)' },
  { value: 'BE', label: 'Belgium (BE)' },
  { value: 'CN', label: 'China (CN)' },
  { value: 'JP', label: 'Japan (JP)' },
  { value: 'IN', label: 'India (IN)' },
  { value: 'BR', label: 'Brazil (BR)' },
  { value: 'CA', label: 'Canada (CA)' },
  { value: 'AU', label: 'Australia (AU)' }
];
